### ISSUE TITLE
[feature request] make this library extendible

### ISSUE THREAD

**Issue by Evertt** [locoslab/vue-typescript-component#13]
Hi,

I'm starting to like this library much more than the official one from VueJS. The only little down-side is, this library isn't in any way extendible. What I would like to do is write property decorators for vuex-stuff, [like this guy has done](https://github.com/ktsn/vuex-class/), as an extension for this library.

So that means I would need to have a hook of sorts that I can use to tell this library to let me influence the vue-component its building. I'm willing to rewrite this library myself to create such a hook if you are too busy for it. :-)

**Comment by locobert** [comment]
Sorry for the long overdue reply. The TypeScript bindings in Vue.js have changed considerably over time and we do not use the approach of this repository anymore. We recommend to use the official TypeScript support and get started with [Vue CLI](https://cli.vuejs.org/)
