### ISSUE TITLE
some attr should not be reactive

### ISSUE THREAD

**Issue by zuomingcai** [locoslab/vue-typescript-component#14]
currently,all attributes in vts object are made reactive,
can vts add some decoartions to mark some attributes not te be reactvie?

**Comment by locobert** [comment]
Sorry for the long overdue reply. The TypeScript bindings in Vue.js have changed considerably over time and we do not use the approach of this repository anymore. We recommend to use the official TypeScript support and get started with [Vue CLI](https://cli.vuejs.org/)
