### ISSUE TITLE
Custom name for components

### ISSUE THREAD

**Issue by CKGrafico** [locoslab/vue-typescript-component#24]
Probably we didn't understand this well but we can't do components with custom name:

Example:

this doesn't work
----------
```
@vts.component()
export default class Name2 extends Vue {
    name = 'name1';
}
<name1></name1>
```
this doesn't work
----------
```
@vts.component({name: 'name1'})
export default class Name2 extends Vue {

}
<name1></name1>
```

this works
--------

```
@vts.component()
export default class Name2 extends Vue {
}
<name2></name2>
```

**Comment by locobert** [comment]
Sorry for the long overdue reply. The TypeScript bindings in Vue.js have changed considerably over time and we do not use the approach of this repository anymore. We recommend to use the official TypeScript support and get started with [Vue CLI](https://cli.vuejs.org/)
