### ISSUE TITLE
not compatible with vee-validate

### ISSUE THREAD

**Issue by zuomingcai** [locoslab/vue-typescript-component#4]
vee-validate does not work with vue-type-component.

vee-validate:https://github.com/logaretm/vee-validate

**Comment by locobert** [comment]
It would be very helpful if you could elaborate what your issue is and provide an example.

If it is about accessing the variables injected by the plugin, you need a definition for the type of `$validator` and then the following should work:

``` typescript
@vts.component()
export default class Example extends Vue {
    $validator: YourValidatorTypeDefinition
//...
}
```

**Comment by zuomingcai** [comment]
vee injected var:$validator & errors，errors is defined by defineproperty which is directed to  $validator.errors，it works fine without vts，if with vts，validate errors can be found in  $validator.errors，but not in errors.

**Comment by locobert** [comment]
It works for me

I've adapted the introductory vee-validate example:

ts.vue:

``` html
<template>
<div class="column is-12">
    <label class="label" for="email">Email</label>
    <p :class="{ 'control': true }">
        <input v-validate data-rules="required|email" :class="{'input': true, 'is-danger': errors.has('email') }" name="email" type="text" placeholder="Email">
        <span v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</span>
    </p>
    <button v-on:click.prevent='dbg'>ShowError</button>
</div>
</template>

<script>
module.exports = require('./ts.ts').default.vueComponentOptions
</script>
```

ts.ts

``` typescript
import Vue = require('vue')
import * as vts from 'vue-typescript-component'

@vts.component()
export default class Ts extends Vue {
    // declaring 'errors' would make cast below unnecessary
    // errors: any
    dbg() {
      console.log(JSON.stringify((<any>this).errors))
    }
}

```

Both the error message on the web page, whose template uses the `errors` field, and the output of the console after clicking the button work:

```
{"errors":[{"field":"email","msg":"The email must be a valid email."}]}
```

**Comment by zuomingcai** [comment]
i build a new project and test your code,still didn't work,
attached is the project source file and builded file.

[build.zip](https://github.com/locoslab/vue-typescript-component/files/585543/build.zip)
[my-project.zip](https://github.com/locoslab/vue-typescript-component/files/585544/my-project.zip)

**Comment by locobert** [comment]
Thanks for the project.

As it turns out, the issue is using the ES6 target for TypeScript. To build the `data()` function for Vue, vts uses the return value of `new cls()` (e.g., `new App()`). However, with target=ES6 that value includes the `errors` (and `fields`) field injected by vee, which leads to the problem.

I have added a new decorator `@injected` to mark a field and prevent it from inclusion in data. Therefore, either change `"target": "es6"` to `"target": "es5"` in `tsconfig.json` or update `vue-typescript-component` to 0.6.0 and change `App.ts` to:

``` TypeScript
import Vue = require('vue')
import * as vts from 'vue-typescript-component'

@vts.component()
export default class App extends Vue {
    // if you have a type for errors, use that instead of any
    @vts.injected() errors: any
    dbg() {
      console.log(JSON.stringify(this.errors))
    }
}
```

**Comment by locobert** [comment]
Please reopen if the issue persists
