### ISSUE TITLE
webpack?

### ISSUE THREAD

**Issue by davidmoshal** [locoslab/vue-typescript-component#9]
Hi, am evaluating Vue 2.0 alternatives to `vue-typescript` (which seems to be dormant on Vue 1.0), and am wondering whether you have an example using `webpack` and `jest` (instead of browserify and jest).

Thanks

David

**Comment by locobert** [comment]
Hi David,

we are not using Webpack internally. I took a quick stab at it using the vue-cli webpack template. You can have a look at result here: https://github.com/locobert/vue-typescript-component-example-webpack

Besides adding the dependencies and a `tsconfig.json`, the actual [change](https://github.com/locobert/vue-typescript-component-example-webpack/commit/610f700e60750eddb645d800051b6175c80a280d#diff-8dc8796144fc0bf0dc97a14a920bbe66) to the build configuration file has been quite small. The source code and the tests are from our [browserify example](https://github.com/locoslab/vue-typescript-component-example).

However, we currently do not plan to maintain that example and it has not been thoroughly tested.

**Comment by locobert** [comment]
Please reopen if you have more questions.
